config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path_names: { sign_up: 'register' }
  
  # Games
  resources :games
  
  # Roles
  resources :roles
  
  # Communities
  resources :communities do
    member do
      get :join
      get :leave
    end
  end
  
  # Team
  resources :teams do
    member do
      get :join
      get :leave
    end
    
    resources :games
  end
  
  # Gamers
  resources :gamers, only: [:index, :show, :edit, :update] do
    collection do
      get :search
      match :search_results, via: [:get, :post]
    end
    
    resources :communities
    resources :teams
  end
  
  resources :memberships do
    member do
      get :approve
      get :decline
      get :ban
      get :unban
      
      get :change_role
    end
  end
  
  # Events
  resources :events do
    post :change_participation, on: :member
  end
  
  # API specifics
  namespace :api do
    resources :gamers, only: [:index]
  end
  
  authenticated(:user) do
    get '/', to: 'gamers#home', as: :user_root
    
    namespace :settings do
      get :gamer
      match :update_gamer, via: [:patch, :put]
      get :user
      match :update_user, via: [:patch, :put]
      get :identities
    end
    
    # FIXME: Play with simplified UI
    get '/play', to: 'play#index'
    match :play_results, via: [:get, :post], to: 'play#results'

    get '/organize', to: 'organize#index'
    get '/explore', to: 'explore#index'
    
    # TODO: Move static pages outside authenticated block
    # Static pages
    get '/about', to: 'pages#about'
    get '/partners', to: 'pages#partners'
    get '/developers', to: 'pages#developers'
    
    # Legal stuff
    get '/terms-of-service', to: 'pages#terms_of_service'
    get '/privacy-policy', to: 'pages#privacy_policy'
    get '/cookie-policy', to: 'pages#cookie_policy'
    
    get '/kitchensink', to: 'pages#kitchensink'
    
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
    resources :users
    match '/become_user/:id', to: 'users#become_user', as: :become_user, via: [:get, :post]
    match '/become_self', to: 'users#become_self', as: :become_self, via: [:get, :post]
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
  end

  # Only for Core
  authenticate :user, lambda { |u| u.is_core? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  
  root 'pages#homepage'
end

app/models/membership.rb
class Membership < ApplicationRecord
  self.inheritance_column = :x
  acts_as_paranoid
  
  include PrivacySupport
  
  enum status: [:pending, :approved, :declined, :banned, :left]
  enum type: [:unknown, :gamer_in_team, :gamer_in_community, :team_in_community]
  
  # Relations
  belongs_to :community, optional: true
  belongs_to :team, optional: true
  belongs_to :gamer, optional: true
  belongs_to :role
  
  # Scopes
  scope :for_communities, -> { where(type: [:gamer_in_community, :team_in_community]) }
  scope :for_community, ->(community) { where(community_id: community.id) }
  
  scope :for_teams, -> { where(type: [:gamer_in_team, :team_in_community]) }
  scope :for_team, ->(team) { where(team_id: team.id) }
  
  scope :for_gamers, -> { where(type: [:gamer_in_team, :gamer_in_community]) }
  scope :for_gamer, ->(gamer) { where(gamer_id: gamer.id) }
  
  # TODO: Improve this and extract to concern
  def self.privacy_filter(gamer_id = nil, team_ids = [], community_ids = [])
    where(arel_table[:privacy].eq(:anyone).
      or(arel_table[:privacy].eq(:me_only).
        and(arel_table[:gamer_id].eq(gamer_id))).
      or(arel_table[:privacy].in([:team_only, :team_or_community]).
        and(arel_table[:type].in([:gamer_in_team])).
        and(arel_table[:team_id].in(team_ids))).
      or(arel_table[:privacy].in([:community_only, :team_or_community]).
        and(arel_table[:type].in([:gamer_in_community, :team_in_community])).
        and(arel_table[:community_id].in(community_ids)))
    )
  end

  # FIXME: Find a better way
  scope :for_entity, ->(entity) {
    case entity.class
    when Team then for_teams(entity)
    when Community then for_community(entity)
    end
  }
  
  def entity
    case
    when gamer_in_team? then team
    when gamer_in_community?, team_in_community? then community
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.all.decorate
    # authorize Membership
  end
  
  def show
    @membership = Membership.find(params[:id])
    authorize @membership
  end
  
  def new
    @membership = Membership.new
    authorize @membership
    
    render 'form'
  end
  
  def create
    @membership = Membership.new(membership_params)
    authorize @membership
    
    if @membership.save
      redirect_to membership_path(@membership)
    else
      render 'form'
    end
  end
  
  def edit
    @membership = Membership.find(params[:id])
    authorize @membership
    
    render 'form'
  end
  
  def update
    @membership = Membership.find(params[:id])
    authorize @membership
    
    if @membership.update_attributes(membership_params)
      redirect_to membership_path(@membership)
    else
      render 'form'
    end
  end
  
  def destroy
    @membership = Membership.find(params[:id])
    authorize @membership
    
    if @membership.destroy
      redirect_to memberships_path
    else
      redirect_to :back, alert: 'Destroy failed'
    end
  end
  
  # = Non-CRUD
  
  # FIXME: Refactor this
  def approve
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.update_attribute(:status, :approved)
    
    redirect_to :back
  end
  
  # FIXME: Refactor this
  def decline
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.update_attribute(:status, :declined)
    
    redirect_to :back
  end
  
  # FIXME: Refactor this
  def ban
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.update_attribute(:status, :banned)
    
    redirect_to :back
  end
  
  # FIXME: Refactor this
  def unban
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.update_attribute(:status, :pending)
    
    redirect_to :back
  end
  
  # FIXME: Refactor this
  def change_role
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.update_attribute(:role_id, params[:role_id])
    
    redirect_to :back
  end
  
  private
  
  def membership_params
    params.require(:membership).permit! # FIXME
  end
  
  def arel
    Membership.arel_table
  end
end

app/views/memberships/_manage.haml
- m = membership
.btn-group
  - case m.status.to_sym
    - when :pending
      = link_to fa_icon('thumbs-o-up', text: 'Approve'), approve_membership_path(m), class: 'btn btn-success'
      = link_to fa_icon('thumbs-o-down', text: 'Decline'), decline_membership_path(m), class: 'btn btn-danger'
    - when :approved
      .btn-group
        %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
          = fa_icon('edit', text: 'Change role')
          %span.caret
        %ul.dropdown-menu
          - Role.all.each do |role|
            - next if role.id == m.role_id
            %li= link_to role.to_label, change_role_membership_path(m, role_id: role.id), class: 'dropdown-item'
    - when :banned
      = link_to fa_icon('unlock', text: 'Unban'), unban_membership_path(m), class: 'btn btn-success'
- unless m.status.to_sym == :banned
  = link_to fa_icon('gavel', text: 'Ban'), ban_membership_path(m), class: 'btn btn-danger'

app/views/memberships/_membership.haml
%tr
  %td= link_to(membership.community&.to_label, membership.community) if membership.community
  %td= link_to(membership.team&.to_label, membership.team) if membership.team
  %td= link_to(membership.gamer&.to_label, membership.gamer) if membership.gamer
  %td= link_to(membership.role&.to_label, membership.role) if membership.role
  %td= membership.type
  %td= yes_or_no membership.active
  %td= membership.privacy_label
  %td= membership.status_label
  %td= membership.created_at
  %td= membership.updated_at
  %td
    = render partial: 'shared/crud_actions', locals: { model: membership }

app/views/memberships/_summary_table.haml
- memberships ||= []
%table.table.table-bordered
  %tbody
    - memberships.each do |m|
      - target = m.gamer_in_team? ? m.team : m.community
      %tr
        %td
          %strong= team_or_community_label(target)
        %td= m.role.to_label
        %td= m.status_label
        %td= render partial: 'shared/crud_actions', locals: { model: target }

app/views/memberships/form.haml
= simple_form_for @membership do |f|
  = f.association :community
  = f.association :team
  = f.association :gamer
  = f.association :role, include_blank: false
  = f.input :type, collection: Membership.types.keys.to_a, include_blank: false
  = f.input :active
  = f.input :privacy, collection: Membership.privacies.keys.to_a, include_blank: false
  = f.input :status, collection: Membership.statuses.keys.to_a, include_blank: false
  = f.submit

app/views/memberships/index.haml
.page-header
  %h1
    Memberships
    .pull-right
      = link_to 'New', new_membership_path, class: 'btn btn-primary'
%table.table
  %thead
    %tr
      %th Community
      %th Team
      %th Gamer
      %th Role
      %th Membership Type
      %th Active
      %th Privacy
      %th Status
      %th Created at
      %th Updated at
  %tbody
    = render @memberships

app/views/memberships/show.haml
= @membership.inspect