config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path_names: { sign_up: 'register' }
  
  # Games
  resources :games
  
  # Roles
  resources :roles
  
  # Communities
  resources :communities do
    member do
      get :join
      get :leave
    end
  end
  
  # Team
  resources :teams do
    member do
      get :join
      get :leave
    end
    
    resources :games
  end
  
  # Gamers
  resources :gamers, only: [:index, :show, :edit, :update] do
    collection do
      get :search
      match :search_results, via: [:get, :post]
    end
    
    resources :communities
    resources :teams
  end
  
  resources :memberships do
    member do
      get :approve
      get :decline
      get :ban
      get :unban
      
      get :change_role
    end
  end
  
  # Events
  resources :events do
    post :change_participation, on: :member
  end
  
  # API specifics
  namespace :api do
    resources :gamers, only: [:index]
  end
  
  authenticated(:user) do
    get '/', to: 'gamers#home', as: :user_root
    
    namespace :settings do
      get :gamer
      match :update_gamer, via: [:patch, :put]
      get :user
      match :update_user, via: [:patch, :put]
      get :identities
    end
    
    # FIXME: Play with simplified UI
    get '/play', to: 'play#index'
    match :play_results, via: [:get, :post], to: 'play#results'

    get '/organize', to: 'organize#index'
    get '/explore', to: 'explore#index'
    
    # TODO: Move static pages outside authenticated block
    # Static pages
    get '/about', to: 'pages#about'
    get '/partners', to: 'pages#partners'
    get '/developers', to: 'pages#developers'
    
    # Legal stuff
    get '/terms-of-service', to: 'pages#terms_of_service'
    get '/privacy-policy', to: 'pages#privacy_policy'
    get '/cookie-policy', to: 'pages#cookie_policy'
    
    get '/kitchensink', to: 'pages#kitchensink'
    
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
    resources :users
    match '/become_user/:id', to: 'users#become_user', as: :become_user, via: [:get, :post]
    match '/become_self', to: 'users#become_self', as: :become_self, via: [:get, :post]
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
  end

  # Only for Core
  authenticate :user, lambda { |u| u.is_core? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  
  root 'pages#homepage'
end

app/views/shared/_bottom_context_menu.haml
:css
  body { padding-bottom: 70px; }
%nav.navbar.navbar-default.navbar-fixed-bottom
  .container
    = yield

app/views/shared/_crud_actions.haml
- model ||= nil
.btn-group
  - if policy(model).show?
    = link_to fa_icon('eye'), polymorphic_path(model), class: 'btn btn-default'
  - if policy(model).update?
    = link_to fa_icon('edit'), edit_polymorphic_path(model), class: 'btn btn-default' 
  - if policy(model).destroy?
    = link_to fa_icon('trash'), polymorphic_path(model), method: :delete, class: 'btn btn-danger'

app/views/shared/_main_menu.haml
%nav.navbar.navbar-fixed-top.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ 'data-toggle' => 'collapse', 'data-target' => '#top_menu' }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path }
        = fa_icon('gamepad')
        Gaming Base
        %sup
          &alpha;
    -#&beta;
    #top_menu.collapse.navbar-collapse
      - if user_signed_in?
        = render 'shared/private_menu'
      - else
        = render 'shared/public_menu'

app/views/shared/_private_menu.haml
%ul.nav.navbar-nav
  %form.navbar-form.navbar-left
    .form-group
      %input.form-control{ type: 'text', placeholder: t('private_menu.search_placeholder') }
  %li.nav-item{ class: controller_name == 'play' && action_name == 'index' ? "active" : '' }
    = link_to fa_icon('gamepad', text: t('private_menu.play')), play_path, class: 'nav-link'
  %li.nav-item{ class: controller_name == 'organize' && action_name == 'index' ? "active" : '' }
    = link_to fa_icon('calendar', text: t('private_menu.organize')), organize_path, class: 'nav-link'
  %li.nav-item{ class: controller_name == 'explore' && action_name == 'index' ? "active" : '' }
    = link_to fa_icon('magic', text: t('private_menu.explore')), explore_path, class: 'nav-link'
%ul.nav.navbar-nav.pull-right
  - if session[:became_user] && session[:superuser_id]
    %li.nav-item= link_to fa_icon('back', text: 'Become self'), become_self_path, class: 'btn btn-secondary-outline'
  %li.dropdown
    %a.dropdown-toggle{ href: "#", 'data-toggle' => "dropdown" }
      = fa_icon('photo', text: current_gamer.username)
      %span.caret
    %ul.dropdown-menu
      %li= link_to fa_icon('user', text: t('user_menu.gamer')), gamer_path(current_gamer)
      %li= link_to fa_icon('cogs', text: t('user_menu.settings')), settings_gamer_path
      %li.divider
      %li= link_to fa_icon('sign-out', text: t('user_menu.sign_out')), destroy_user_session_path, class: 'nav-link', method: :delete

app/views/shared/_public_menu.haml
- if Rails.env.development? || Rails.env.production? # FIXME
  %ul.nav.navbar-nav.pull-right
    %li.nav-item
      = link_to 'Register', new_user_registration_path, class: 'btn btn-primary-outline'
    %li.nav-item
      = link_to fa_icon('sign-in', text: 'Sign In'), new_user_session_path, class: 'btn btn-secondary-outline'