config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path_names: { sign_up: 'register' }
  
  # Games
  resources :games
  
  # Roles
  resources :roles
  
  # Communities
  resources :communities do
    member do
      get :join
      get :leave
    end
  end
  
  # Team
  resources :teams do
    member do
      get :join
      get :leave
    end
    
    resources :games
  end
  
  # Gamers
  resources :gamers, only: [:index, :show, :edit, :update] do
    collection do
      get :search
      match :search_results, via: [:get, :post]
    end
    
    resources :communities
    resources :teams
  end
  
  resources :memberships do
    member do
      get :approve
      get :decline
      get :ban
      get :unban
      
      get :change_role
    end
  end
  
  # Events
  resources :events do
    post :change_participation, on: :member
  end
  
  # API specifics
  namespace :api do
    resources :gamers, only: [:index]
  end
  
  authenticated(:user) do
    get '/', to: 'gamers#home', as: :user_root
    
    namespace :settings do
      get :gamer
      match :update_gamer, via: [:patch, :put]
      get :user
      match :update_user, via: [:patch, :put]
      get :identities
    end
    
    # FIXME: Play with simplified UI
    get '/play', to: 'play#index'
    match :play_results, via: [:get, :post], to: 'play#results'

    get '/organize', to: 'organize#index'
    get '/explore', to: 'explore#index'
    
    # TODO: Move static pages outside authenticated block
    # Static pages
    get '/about', to: 'pages#about'
    get '/partners', to: 'pages#partners'
    get '/developers', to: 'pages#developers'
    
    # Legal stuff
    get '/terms-of-service', to: 'pages#terms_of_service'
    get '/privacy-policy', to: 'pages#privacy_policy'
    get '/cookie-policy', to: 'pages#cookie_policy'
    
    get '/kitchensink', to: 'pages#kitchensink'
    
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
    resources :users
    match '/become_user/:id', to: 'users#become_user', as: :become_user, via: [:get, :post]
    match '/become_self', to: 'users#become_self', as: :become_self, via: [:get, :post]
    # TODO: THIS MUST BE CORRECTLY SECURED!!!
  end

  # Only for Core
  authenticate :user, lambda { |u| u.is_core? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  
  root 'pages#homepage'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def gamer
    @gamer = current_gamer
  end
  
  def update_gamer
    @gamer = current_user.gamer
    
    # FIXME: Maybe not use the nested attributes here?
    @gamer.language_proficiencies.each do |lp|
      action = lp.id.blank? ? :create? : :update?
      authorize lp, action
    end
  
    if @gamer.update_attributes(gamer_params)
      redirect_back(fallback_location: root_path)
    else
      render action: :gamer
    end
  end
  
  def user
    @user = current_user
  end
  
  def update_user
    @user = current_user
  
    if @user.update_attributes(user_params)
      redirect_back(fallback_location: root_path)
    else
      render action: :user
    end
  end
  
  def identities
    @identities = current_user.identities
  end
  
  private
  
  def gamer_params
    params.require(:gamer).permit(:username, :dedication, :weekday_availability, :weekend_availability, 
                                  :swearing, :swearing_tolerance, :privacy, :description, 
                                  :first_name, :middle_name, :last_name, :birth_date, :sex, :age, game_ids: [], 
                                  language_proficiencies_attributes: [:id, :gamer_id, :language, :native, 
                                                                      :understanding, :speaking, :writing])
  end
  
  def user_params
    params.require(:user).permit(:locale, :time_zone)
  end
end

app/views/settings/_language_proficiency_fields.haml
.nested-fields.col-md-3
  = f.input :language, collection: Settings.locales
  = f.input :native
  = f.input :understanding, collection: LanguageProficiency.understandings.keys.to_a, as: :radio_buttons
  = f.input :speaking, collection: LanguageProficiency.speakings.keys.to_a, as: :radio_buttons
  = f.input :writing, collection: LanguageProficiency.writings.keys.to_a, as: :radio_buttons
  = link_to_remove_association "remove language proficiency", f

app/views/settings/_nav.haml
%ul.nav.nav-tabs.nav-justified
  %li{ class: action_name == 'index' || action_name == 'gamer' ? 'active' : '' }
    = link_to 'Gamer', settings_gamer_path
  %li{ class: action_name == 'user' ? 'active' : '' }
    = link_to 'User', settings_user_path
  %li{ class: action_name == 'identities' ? 'active' : '' }
    = link_to 'Identities', settings_identities_path

app/views/settings/gamer.haml
%ol.breadcrumb
  %li= link_to "Home", root_path
  %li= link_to "Settings", '#'
  %li.active Gamer

%h1 Settings
= render partial: 'nav'

= simple_form_for @gamer, url: settings_update_gamer_path do |f|
  .row
    .col-md-4
      %fieldset
        %legend Personal
        = f.input :first_name
        = f.input :middle_name
        = f.input :last_name
        = f.input :birth_date
        = f.input :sex, collection: Gamer.sexes.keys.to_a, as: :radio_buttons
        = f.input :age
    .col-md-4
      %fieldset
        %legend Additional
        = f.input :username, input_html: { disabled: true }
        = f.input :description
        = f.input :dedication, collection: Gamer.dedications.keys.to_a, as: :radio_buttons
        = f.input :weekday_availability, collection: Gamer.weekday_availabilities.keys.to_a, as: :radio_buttons
        = f.input :weekend_availability, collection: Gamer.weekend_availabilities.keys.to_a, as: :radio_buttons
        = f.input :swearing, collection: Gamer.swearings.keys.to_a, as: :radio_buttons
        = f.input :swearing_tolerance, collection: Gamer.swearing_tolerances.keys.to_a, as: :radio_buttons
        = f.input :privacy, collection: Gamer.privacies.keys.to_a, as: :radio_buttons
    .col-md-4
      %fieldset
        %legend Games
        = f.association :games, as: :check_boxes
  .row
    %fieldset
      %legend Language Proficiencies
      #language-proficiencies
        = f.simple_fields_for :language_proficiencies do |lp_form|
          = render 'language_proficiency_fields', f: lp_form
        .links
          = link_to_add_association 'add language proficiency', f, :language_proficiencies

  = render 'shared/bottom_context_menu' do
    %button.btn.btn-success.navbar-btn{ type: "submit" } Save changes

app/views/settings/identities.haml
%ol.breadcrumb
  %li= link_to "Home", root_path
  %li= link_to "Settings", '#'
  %li.active Identities

%h1 Settings
= render partial: 'nav'

- if @identities.blank?
  %h3 No identities.
- else
  %table.table
    %thead
      %tr
        %th User ID
        %th UID
        %th Provider
        %th Created at
        %th Updated at
    %tbody
      = render @identities

app/views/settings/user.haml
%ol.breadcrumb
  %li= link_to "Home", root_path
  %li= link_to "Settings", '#'
  %li.active User

%h1 Settings
= render partial: 'nav'

= simple_form_for @user, url: settings_update_user_path do |f|
  = f.input :locale, collection: [:en, :ru]
  = f.input :time_zone
  
  = render 'shared/bottom_context_menu' do
    %button.btn.btn-success.navbar-btn{ type: "submit" } Save changes